import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = { title: process.env.APP_NAME || "CRM Core", description: "A secure CRM generated by App Factory" };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en"><body>{children}</body></html>;
}
